SWIDEA_SITE/SWIDEA/urls.py
from django.urls import path, include
from . import views

app_name = "SWIDEA"

urlpatterns = [
    path('', views.idea_list, name='idea_list'),
    path('idea/<int:pk>/', views.idea_detail, name='idea_detail'),
    path('idea/new/', views.idea_new, name="idea_new"),
    path('idea/<int:pk>/update/', views.idea_update, name='idea_update'),
    path('idea/<int:pk>/delete/', views.idea_delete, name='idea_delete'),
    path('dev/list/', views.dev_list, name='dev_list'),
    path('dev/<int:pk>/', views.dev_detail, name='dev_detail'),
    path('dev/new/', views.dev_new, name="dev_new"),
    path('dev/<int:pk>/update/', views.dev_update, name='dev_update'),
    path('dev/<int:pk>/delete/', views.dev_delete, name='dev_delete'),
    path('idea/plus/', views.idea_plus, name='idea_plus'),
    path('idea/minus/', views.idea_minus, name='idea_minus'),
]

SWIDEA_SITE/SWIDEA/models.py
from unicodedata import category
from django.db import models

# Create your models here.



class Develop(models.Model):
    title = models.CharField(verbose_name='툴 이름', max_length=50)
    cate = models.CharField(verbose_name='툴 종류', max_length=50)
    content = models.TextField(verbose_name='개발 툴 설명')
    
    def __str__(self):
        return self.title

class Idea(models.Model):
    title = models.CharField(verbose_name='아이디어 명', max_length=50)
    photo = models.ImageField(verbose_name='대표사진', blank=True, null=True, upload_to ='')
    content = models.TextField(verbose_name='아이디어 설명')
    rate = models.IntegerField(verbose_name='아이디어 관심도')
    develop = models.ForeignKey(Develop, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

SWIDEA_SITE/SWIDEA/forms.py
from dataclasses import fields
from django import forms
from .models import *

class IdeaForm(forms.ModelForm):
    class Meta:
        model = Idea
        fields ="__all__"

class DevelopForm(forms.ModelForm):
    class Meta:
        model = Develop
        fields = "__all__"

        

SWIDEA_SITE/SWIDEA/views.py
from http.client import HTTPResponse
from pickle import NONE
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import *
import json
from django.http import JsonResponse
from django.core import serializers

# Create your views here.

def idea_list(request):
    ideaList = Idea.objects.all()
    ctx = {'ideaList': ideaList}
    return render(request, 'SWIDEA/idea_list.html', ctx)


def idea_detail(request, pk):
    idea = Idea.objects.get(pk=pk)
    ctx = {'idea': idea}
    return render(request, 'SWIDEA/idea_detail.html', ctx)


def idea_new(request):
    if request.method == "POST":
        form = IdeaForm(request.POST, request.FILES)
        if form.is_valid():
            new_idea = form.save()
            return idea_detail(request, new_idea.pk)
    else:
        form = IdeaForm()
    
    ctx = {'form': form}
    return render(request, 'SWIDEA/idea_new.html', context=ctx)

def idea_update(request, pk):
    idea = get_object_or_404(Idea, pk=pk)
    
    if request.method == "POST":
        form = IdeaForm(request.POST, request.FILES, instance=idea)
        if form.is_valid():
            idea = form.save(commit=False)
            idea.save()
            return idea_detail(request, idea.pk)
    
    else:
        form = IdeaForm(instance=idea)
        ctx = {'form': form}

        return render(request, 'SWIDEA/idea_update.html', context=ctx)

def idea_delete(request, pk):
    idea = get_object_or_404(Idea, pk=pk)
    idea.delete()

    return redirect('SWIDEA:idea_list')

    ###########################################################################################################

def dev_list(request):
    devList = Develop.objects.all()
    ctx = {'devList': devList}
    return render(request, 'SWIDEA/dev_list.html', ctx)

def dev_detail(request, pk):
    dev = Develop.objects.get(pk=pk)
    idea = Idea.objects.all().filter(develop=dev)
    ctx = {'dev': dev, 'idea': idea}
    return render(request, 'SWIDEA/dev_detail.html', ctx)


def dev_new(request):
    if request.method == "POST":
        form = DevelopForm(request.POST)
        if form.is_valid():
            new_dev = form.save()
            return dev_detail(request, new_dev.pk)
    else:
        form = DevelopForm()
    
    ctx = {'form': form}
    return render(request, 'SWIDEA/dev_new.html', context=ctx)

def dev_update(request, pk):
    dev = get_object_or_404(Develop, pk=pk)
    
    if request.method == "POST":
        form = DevelopForm(request.POST, instance=dev)
        if form.is_valid():
            dev = form.save(commit=False)
            dev.save()
            return dev_detail(request, dev.pk)
    
    else:
        form = DevelopForm(instance=dev)
        ctx = {'form': form}

        return render(request, 'SWIDEA/dev_update.html', context=ctx)

def dev_delete(request, pk):
    dev = get_object_or_404(Develop, pk=pk)
    dev.delete()

    return redirect('SWIDEA:dev_list')


###############################################################################

def idea_plus(request):
    pk = request.POST.get('pk', None)
    idea = get_object_or_404(Idea, pk=pk)

    idea.rate += 1
    idea.save()

    ctx = {'idea_rate': idea.rate}
    return JsonResponse(ctx)

def idea_minus(request):
    pk = request.POST.get('pk', None)
    idea = get_object_or_404(Idea, pk=pk)

    idea.rate -= 1
    idea.save()

    ctx = {'idea_rate': idea.rate}
    return JsonResponse(ctx)

SWIDEA_SITE/SWIDEA/templates/SWIDEA/dev_detail.html
{% extends 'base.html' %}

{% block content %}
<section class="text_center">
    <div class="subHeader">
        <h2>DevTool Detail</h2>
        <h6>개발툴 세부내용 페이지 입니다. 자신이 다룰 수 있는 개발툴에 대한 상세 내용을 확인해보아요.</h6>
    </div>
    <div class="content dev_detail">
        <div class="dev_detail text_left">
            <h2>{{dev.title}}</h2>
            <h4>{{dev.cate}}</h4>
            <h5>{{dev.content}}</h5>
            <h4> > 만들 수 있는 SW목록</h4>
            {% for val in idea.values %}
                <h6><a href="{% url 'SWIDEA:idea_detail' val.id %}">{{val.title}}</a></h6>
            {% endfor %}
        </div>
        <div class="detail_footer">
            <a class="detail_delete" href="{% url 'SWIDEA:dev_delete' dev.pk %}">삭제</a>
            <a class="detail_list" href="{% url 'SWIDEA:dev_list' %}">목록</a>
            <a class="detail_update" href="{% url 'SWIDEA:dev_update' dev.pk %}">수정</a>
        </div>
    </div>
</section>
{% endblock %}

SWIDEA_SITE/SWIDEA/templates/SWIDEA/dev_list.html
{% extends 'base.html' %}
{% block content %}
<section class="text_center">
    <div class="subHeader">
        <h2>DevTool List</h2>
        <h6>개발툴 목록 페이지입니다. 자신이 사용가능한 개발들의 목록을 확인해보세요</h6>
    </div>
    <div class="flex_container">
        {% for dev in devList %}
        <div class="dev_content">
            <div class="dev_explain">
                <h2><a href="{% url 'SWIDEA:dev_detail' pk=dev.pk %}">{{dev.title}}</a></h2>
                <h4>{{dev.cate}}</h4>
                <h6>{{dev.content}}</h6>
            </div>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock %}

SWIDEA_SITE/SWIDEA/templates/SWIDEA/dev_new.html
{% extends 'base.html' %}
{% block content%}
<section class="text_center">
    <div class="subHeader">
        <h2>DevTool Register</h2>
        <h6>개발툴 등록 페이지 입니다. 자신이 다룰 수 있는 개발툴을 등록해보세요.</h6>
    </div>
    <form class="form text_left" method="POST">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <button type = 'submit'>Submit</button>
    </form>
</section>
{% endblock%}

SWIDEA_SITE/SWIDEA/templates/SWIDEA/dev_update.html
{% extends 'base.html' %}
{% block content%}
<section class="text_center">
    <div class="subHeader">
        <h2>DevTool Update</h2>
        <h6>개발툴 세부내용 수정페이지 입니다. 개발툴에 대해 수정사항이 있으면 고쳐보아요</h6>
    </div>
    <form class="form text_left" method="POST">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <button type = 'submit'>Submit</button>
    </form>
</section>
{% endblock%}

SWIDEA_SITE/SWIDEA/templates/SWIDEA/idea_detail.html
{% extends 'base.html' %}

{% block content %}
<section class="text_center">
    <div class="subHeader">
        <h2>Idea Detail</h2>
        <h6>아이디어 세부페이지</h6>
    </div>
    <div class="detail_content">
        {% if idea.photo %}
        <div class="detail_photo">
            <img src="{{ idea.photo.url }}" alt="">
        </div>
        {% endif %}
        <div class="idea_detail">
            <h2>{{idea.title}}</h2>
            <h5>1) 아이디어 관심도: {{idea.rate}}</h5>
            <h5>2) 예상 개발 툴: <br/>
                <a href="{% url 'SWIDEA:dev_detail' idea.develop.pk%}">{{ idea.develop.title }}</a></h5>
            <h5>3) 아이디어 설명:</h5>
            <h6>{{idea.content}}</h6>
        </div>
    </div>
        <div class="detail_footer">
            <a class="detail_delete" href="{% url 'SWIDEA:idea_delete' idea.pk %}">삭제</a>
            <a class="detail_list" href="{% url 'SWIDEA:idea_list' %}">목록</a>
            <a class="detail_update" href="{% url 'SWIDEA:idea_update' idea.pk %}">수정</a>
        </div>
</section>
{% endblock %}

SWIDEA_SITE/SWIDEA/templates/SWIDEA/idea_list.html
{% extends 'base.html' %}
{% block content %}
<section class="text_center">
    <div class="subHeader">
        <h2>Idea List</h2>
        <h6>나의 아이디어를 잊지말고 기록해보세요</h6>
    </div>
    <div class="flex_container">
        {% for idea in ideaList %}
        <div class="content">
            {% if idea.photo %}
            <div class="photo">
                <img src="{{ idea.photo.url }}" alt="">
            </div>
            {% endif %}
            <div class="explain">
                <h2><a href="{% url 'SWIDEA:idea_detail' pk=idea.pk %}">{{idea.title}}</a></h2>
                <h5>예상 개발 툴: <em>{{ idea.develop.title }}</em></h5>
                <div class="btns">
                    <h5 id="count-{{ idea.id }}">아이디어 관심도: {{idea.rate}}</h5>
                    <button class="btn_plus" name="{{ idea.id }}"><i class="far fa-plus-square fa-2x"></i></button>
                    <button class="btn_minus" name="{{ idea.id }}"><i class="far fa-minus-square fa-2x"></i></button>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</section>

<script type="text/javascript">
    $(".btn_plus").click(function(){
        var pk = $(this).attr("name")
        $.ajax({
            type: "POST",
            url: "{% url 'SWIDEA:idea_plus' %}",    
            data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
            dataType: "json",
            success: function(response){
                $("#count-"+pk).text("아이디어 관심도: " + response['idea_rate'])
            }
        })
    })
    $(".btn_minus").click(function(){
        var pk = $(this).attr("name")
        $.ajax({
            type: "POST",
            url: "{% url 'SWIDEA:idea_minus' %}",
            data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
            dataType: "json",
            success: function(response){
                $("#count-"+pk).text("아이디어 관심도: " + response['idea_rate'])
            }
        })
    })
</script>
{% endblock %}

SWIDEA_SITE/SWIDEA/templates/SWIDEA/idea_new.html
{% extends 'base.html' %}
{% block content%}
<section class="text_center">
    <div class="subHeader">
        <h2>Idea Register</h2>
        <h6>아이디어 등록 페이지입니다. 당신의 아이디어를 잊지말고 등록하세요</h6>
    </div>
    <form class="form text_left" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <button type = 'submit'>Submit</button>
    </form>
</section>
{% endblock%}

SWIDEA_SITE/SWIDEA/templates/SWIDEA/idea_update.html
{% extends 'base.html' %}
{% block content%}
<section class="text_center">
    <div class="subHeader">
        <h2>Idea Detail Update</h2>
        <h6>아이디어 세부내용 수정페이지입니다. 아이디어를 구체화하거나 내용을 변경해보아요.</h6>
    </div>
    <form class="form text_left" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <button type = 'submit'>Submit</button>
    </form>
</section>
{% endblock%}

SWIDEA_SITE/SWIDEA/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-latest.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
    <title>My SW Idea Management</title>
</head>
<body>
    <header>
        <h1><a href="{% url 'SWIDEA:idea_list' %}">My SW Idea Management</a></h1>
        <div class="sub">
            <h3><a href="{% url 'SWIDEA:idea_new' %}">아이디어 등록</a></h3>
            <h3><a href="{% url 'SWIDEA:idea_list' %} ">아이디어 관리</a></h3>
            <h3><a href="{% url 'SWIDEA:dev_new' %}">개발툴 등록</a></h3>
            <h3><a href="{% url 'SWIDEA:dev_list' %}">개발툴 관리</a></h3>
        </div>
    </header>
    <div class="center-align">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>