myMovieReviews/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

#for image
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('review/', include('review.urls')),
    # path('', view = views.main, name ='main'),
 ]
#set image urls
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myMovieReviews/mysite/review/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'review'

urlpatterns = [
    path('', view = views.review_list, name='list'),
    path('<int:pk>/', view = views.review_detail, name = 'detail'),
    path('create/', view = views.review_create, name = 'create'),
    path('<int:pk>/update/', view = views.review_update, name = 'update'),
    path('<int:pk>/delete/', view = views.review_delete, name = 'delete'),
]

myMovieReviews/mysite/review/models.py
from msilib.schema import Directory
from django.db import models

class Review(models.Model):
    action = '액션'
    drama = '드라마'
    fantasy = '판타지'
    comedy = '코미디'
    animation = '애니메이션'

    title = models.CharField(verbose_name='제목', max_length=100)
    year = models.CharField(verbose_name='개봉년도', max_length=10)
    GENRE_IN_CHOICES = (
        (action, '액션'),
        (drama, '드라마'),
        (fantasy, '판타지'),
        (comedy, '코미디'),
        (animation, '애니메이션')
    )

    genre = models.CharField(verbose_name='장르', max_length=10, choices=GENRE_IN_CHOICES, default=action)

    rate = models.FloatField(verbose_name='평점', max_length=10)
    time = models.CharField(verbose_name='러닝타임', max_length=10)
    content = models.TextField(verbose_name='내용')
    director = models.CharField(verbose_name='감독', max_length=20)
    actor = models.CharField(verbose_name='배우', max_length=20)

    photo = models.ImageField(verbose_name='사진', blank=True, null=True, upload_to="")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

myMovieReviews/mysite/mysite/views.py
from django.shortcuts import render

def main(request):
    return render(request, template_name = 'main.html')

myMovieReviews/mysite/review/views.py
from atexit import register
from django.shortcuts import render, redirect, get_object_or_404
from .models import Review
from .form import PostForm


def review_list(request):
    reviews = Review.objects.all().order_by('-rate')
    ctx = {'reviews': reviews}

    return render(request, template_name = 'list.html', context = ctx)

def review_detail(request, pk):
    review = Review.objects.get(id=pk)
    ctx = {'review': review}
    return render(request, template_name='detail.html', context = ctx)

def review_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('review:list')
    
    else:
        form = PostForm()
        ctx = {'form': form}
        return render(request, template_name = 'update.html', context =ctx)


def review_update(request, pk):
    review = get_object_or_404(Review, id=pk)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance = review)
        if form.is_valid():
            review = form.save(commit=False)
            review.save()
        return redirect('review:detail', pk)
    
    else:
        form = PostForm(instance=review)
        ctx = {'form': form}

        return render(request, template_name='update.html', context=ctx)

def review_delete(request, pk):
    review = get_object_or_404(Review, id=pk)
    review.delete()

    return redirect('review:list')

myMovieReviews/mysite/review/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Jua&display=swap" rel="stylesheet">
    <title>My Movie Reviews </title>
</head>
<body>
    <div class="header">
        <h1><a href="/review">my<em>Movie</em>Review</a></h1>
        {% if user.is_authenticated %}
           <a href="{% url 'review:create' %}" class="top-menu"><i class="fas fa-plus fa-2x"></i></a>
 
        {% endif %}
    </div>
    <div class="content-container center-align">
        {% block content %}
        {% endblock %}
    </div>


</body>
</html>

myMovieReviews/mysite/review/templates/detail.html
{% extends 'base.html' %}
{% load time_format%}

{% block content %}
    <div class="detail">
        {% if review.photo %}
            <img src = "{{ review.photo.url }}" alt="" height="500">
        {% endif %}
        <div class="detail_content">
            <h1>{{review.title}}</h1>
            <h4>개봉년도: {{review.year}}</h4>
            <h4>감독: {{review.director}}</h4>
            <h4>장르: {{review.genre}}</h4>
            <h4>별점: {{review.rate}}</h4>
            <h4>러닝타임: {{review.time|time_format}}</h4>
            <div class="detail_review">
                {{review.content}}
            </div>
            <div class="btns">
                <a href="{% url 'review:update' review.id %}">수정하기</a>
                <a href="{% url 'review:delete' review.id %}">삭제하기</a>
            </div>
        </div>
    </div>
        
{% endblock %}

myMovieReviews/mysite/review/templates/list.html
{% extends 'base.html' %}


{% block content %}
    <div class="review">
        {% for review in reviews %}
        <div class="content">
            {% if review.photo %}
            <div class="photo">
                <img src = "{{ review.photo.url }}" alt="" height="300">
            </div>
            {% endif %}
            <div class="explain">
                <h2><a href="{% url 'review:detail' review.id %}">{{review.title}}</a></h2>
                <h5>개봉년도: {{review.year}}</h5>
                <h5>장르: {{review.genre}}</h5>
                <h5>별점: {{review.rate}}</h5>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

myMovieReviews/mysite/review/templates/update.html
{% extends 'base.html' %}

{% block content %}
<div class="center-align update">
    <form action="" method = "POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
    
        <input class="submit_btn" type="submit" value="저장하기" />
    </form>
</div>
{% endblock %}